name: Node.js CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - name: checkout the repo
         uses: actions/checkout@v3

       - name: install Node js
         uses: actions/setup-node@v3
         with:
          node-version: '22'
       - name: Install pakages
         run: npm install 

       - name: test the Application 
         run: npm run check
      